apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    uid: tempo

  - name: Prometheus (Exemplars)
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus-exemplars
    jsonData:
      tracesToLogsV2:
        datasourceUid: tempo
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo
