// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Metrics is an autogenerated mock type for the Metrics type
type Metrics struct {
	mock.Mock
}

// DecTasksCount provides a mock function with given fields: ctx, status, reason
func (_m *Metrics) DecTasksCount(ctx context.Context, status string, reason string) {
	_m.Called(ctx, status, reason)
}

// IncTaskCreated provides a mock function with given fields: ctx, status, reason
func (_m *Metrics) IncTaskCreated(ctx context.Context, status string, reason string) {
	_m.Called(ctx, status, reason)
}

// IncTaskDeleted provides a mock function with given fields: ctx, status, reason
func (_m *Metrics) IncTaskDeleted(ctx context.Context, status string, reason string) {
	_m.Called(ctx, status, reason)
}

// IncTaskFetched provides a mock function with given fields: ctx, status, source
func (_m *Metrics) IncTaskFetched(ctx context.Context, status string, source string) {
	_m.Called(ctx, status, source)
}

// IncTaskListed provides a mock function with given fields: ctx, status
func (_m *Metrics) IncTaskListed(ctx context.Context, status string) {
	_m.Called(ctx, status)
}

// IncTaskUpdated provides a mock function with given fields: ctx, status, reason
func (_m *Metrics) IncTaskUpdated(ctx context.Context, status string, reason string) {
	_m.Called(ctx, status, reason)
}

// IncTasksCount provides a mock function with given fields: ctx, status, reason
func (_m *Metrics) IncTasksCount(ctx context.Context, status string, reason string) {
	_m.Called(ctx, status, reason)
}

// RecordTaskCreatedDuration provides a mock function with given fields: ctx, duration
func (_m *Metrics) RecordTaskCreatedDuration(ctx context.Context, duration float64) {
	_m.Called(ctx, duration)
}

// RecordTaskDeletedDuration provides a mock function with given fields: ctx, duration
func (_m *Metrics) RecordTaskDeletedDuration(ctx context.Context, duration float64) {
	_m.Called(ctx, duration)
}

// RecordTaskFetchedDuration provides a mock function with given fields: ctx, duration
func (_m *Metrics) RecordTaskFetchedDuration(ctx context.Context, duration float64) {
	_m.Called(ctx, duration)
}

// RecordTaskListedDuration provides a mock function with given fields: ctx, duration
func (_m *Metrics) RecordTaskListedDuration(ctx context.Context, duration float64) {
	_m.Called(ctx, duration)
}

// RecordTaskUpdatedDuration provides a mock function with given fields: ctx, duration
func (_m *Metrics) RecordTaskUpdatedDuration(ctx context.Context, duration float64) {
	_m.Called(ctx, duration)
}

// NewMetrics creates a new instance of Metrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *Metrics {
	mock := &Metrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
